services:
- docker
script:
- mvn -Dmaven.test.skip=true package
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker build -t cacadosman/online-training:future .
- docker push cacadosman/online-training:future
- ssh -i ./deploy_key cacadosman@202.43.92.132 'cd /home/cacadosman/future-online-training/; ls; docker-compose down; docker-compose pull; docker-compose up -d'
before_install:
- openssl aes-256-cbc -K $encrypted_add5053b7f67_key -iv $encrypted_add5053b7f67_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host 202.43.92.132\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
