services:
- docker
script:
- mvn -Dmaven.test.skip=true package
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker build -t cacadosman/online-training:future .
- docker push cacadosman/online-training:future

before_install:
- openssl aes-256-cbc -K $encrypted_add5053b7f67_key -iv $encrypted_add5053b7f67_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key cacadosman@komatikugm.web.id pwd
