version: "2"
services:
  postgres-service:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=future
      - POSTGRES_USER=future
      - POSTGRES_PASSWORD=future
    networks:
      - backend

  app:
    image: cacadosman/online-training:future
    restart: always
    ports:
      - "0.0.0.0:13370:8080"
    volumes:
      - ./storages/:/var/www/storages/
    networks:
      - backend
    links:
      - postgres-service
      - redis
    depends_on:
      - postgres-service
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storages/:/var/www/storages/
    ports:
      - "0.0.0.0:13371:80"
    networks:
      - backend

  redis:
    image: redis
    expose:
      - "6379"
    networks:
      - backend

networks:
  backend:
