version: "2"
services:
  postgres-service:
    image: postgres
    restart: always
    expose:
      - "5432"
    networks:
      - backend

  app:
    build: .
    restart: always
    ports:
      - "0.0.0.0:13370:8080"
    networks:
      - backend
    links:
      - postgres-service
    depends_on:
      - postgres-service

networks:
  backend:
