version: "2"
services:
  postgres-service:
    image: postgres
    restart: always
    expose:
      - "5432"
    networks:
      - backend

  app:
    build: .
    restart: always
    ports:
      - "0.0.0.0:13370:8080"
    volumes:
      - ./storages/:/var/www/storages/
    networks:
      - backend
    links:
      - postgres-service
    depends_on:
      - postgres-service

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storages/:/var/www/storages/
    ports:
      - "0.0.0.0:13371:80"
    networks:
      - backend

networks:
  backend:
